name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-restore
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: pack/Release/netcoreapp3.1/

  publish:
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/chwarr/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Download packages
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages
        path: pack/
    - name: what
      run: find .
    - name: Push
      run: dotnet nuget push "pack/*.nupkg"
