name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-restore
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: pack/Release/netcoreapp3.1/

  integration-tests:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Download packages
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages
        path: pack/
    - name: Test (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        Set-StrictMode -Version Latest
        Set-PsDebug -Trace 1
        $dnjcVersion = "0.0.1-ci.$env:GITHUB_RUN_ID"
        $dnjcPath = & tests\integration-tests\windows\Install-Dnjc.ps1 -SourceDir .\pack\ -Version $dnjcVersion
        & tests\integration-tests\windows\Test-Dnjc.ps1 -DnjcPath $dnjcPath
      shell: pwsh
    - name: Test (Unixy)
      if: ${{ runner.os != 'Windows' }}
      run: |
          set -efu
          dnjc_version="0.0.1-ci.${GITHUB_RUN_ID}"
          dnjc_path=$(./tests/integration-tests/unixy/install-dnjc.sh -s ./pack -v "${dnjc_version}")
          ./tests/integration-tests/unixy/test-dnjc.sh -d "${dnjc_path}"

  publish:
    if: ${{ github.event_name == 'push' }}
    needs: [build, integration-tests]
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/chwarr/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Download packages
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages
        path: pack/
    - name: Push
      run: dotnet nuget push "pack/*.nupkg"
